/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2026-09-29 06:06:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

public final class attendance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("java.time.LocalTime");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");


    Integer Staff_ID =
        (Integer) session.getAttribute("Staff_ID");

    String Staff_Name =
        (String) session.getAttribute("Staff_Name");

    if (Staff_ID == null || Staff_Name == null) {
        response.sendRedirect("Login.html");
        return;
    }

    String message = "";
    boolean alreadyRegistered = false;

    LocalDate today = LocalDate.now();

    DateTimeFormatter dateFormatter =
        DateTimeFormatter.ofPattern("dd MMMM yyyy");

    String formattedDate =
        today.format(dateFormatter);

    Connection con = null;
    PreparedStatement psmt = null;
    ResultSet rs = null;

    String todayStatus = "Not Registered";
    String todayCheckIn = "--";

    try {

        Class.forName("org.postgresql.Driver");

        con = DriverManager.getConnection(
            "jdbc:postgresql://localhost:5432/demoDB",
            "postgres",
            "0617"
        );

        String action =
            request.getParameter("action");

        if ("register".equals(action)) {

            psmt = con.prepareStatement(
                "SELECT * FROM attendance " +
                "WHERE staff_id = ? " +
                "AND attendance_date = ?"
            );

            psmt.setInt(
                1,
                Staff_ID
            );

            psmt.setDate(
                2,
                Date.valueOf(today)
            );

            rs =
                psmt.executeQuery();

            if (rs.next()) {

                message =
                    "Attendance has already been registered for today.";

            } else {

                LocalTime currentTime =
                    LocalTime.now();

                psmt = con.prepareStatement(
                    "INSERT INTO attendance " +
                    "(staff_id, attendance_date, check_in_time, status) " +
                    "VALUES (?, ?, ?, ?)"
                );

                psmt.setInt(
                    1,
                    Staff_ID
                );

                psmt.setDate(
                    2,
                    Date.valueOf(today)
                );

                psmt.setTime(
                    3,
                    Time.valueOf(currentTime)
                );

                psmt.setString(
                    4,
                    "Present"
                );

                int result =
                    psmt.executeUpdate();

                if (result > 0) {

                    message =
                        "Attendance registered successfully.";

                } else {

                    message =
                        "Attendance registration failed.";
                }
            }
        }

        psmt = con.prepareStatement(
            "SELECT * FROM attendance " +
            "WHERE staff_id = ? " +
            "AND attendance_date = ?"
        );

        psmt.setInt(
            1,
            Staff_ID
        );

        psmt.setDate(
            2,
            Date.valueOf(today)
        );

        rs =
            psmt.executeQuery();

        if (rs.next()) {

            alreadyRegistered = true;

            todayStatus =
                rs.getString("status");

            Time checkTime =
                rs.getTime("check_in_time");

            if (checkTime != null) {

                todayCheckIn =
                    checkTime
                    .toLocalTime()
                    .format(
                        DateTimeFormatter.ofPattern("hh:mm a")
                    );
            }
        }

    } catch (Exception e) {

        message =
            "Unable to process attendance. Please try again.";
    }


      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("\n");
      out.write("    <meta name=\"viewport\"\n");
      out.write("          content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("    <title>Staff Attendance</title>\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            min-height: 100vh;\n");
      out.write("            color: white;\n");
      out.write("\n");
      out.write("            background:\n");
      out.write("                radial-gradient(\n");
      out.write("                    circle at top left,\n");
      out.write("                    rgba(99,102,241,0.27),\n");
      out.write("                    transparent 32%\n");
      out.write("                ),\n");
      out.write("                radial-gradient(\n");
      out.write("                    circle at bottom right,\n");
      out.write("                    rgba(14,165,233,0.20),\n");
      out.write("                    transparent 35%\n");
      out.write("                ),\n");
      out.write("                linear-gradient(\n");
      out.write("                    135deg,\n");
      out.write("                    #0f172a,\n");
      out.write("                    #111827,\n");
      out.write("                    #1e293b\n");
      out.write("                );\n");
      out.write("\n");
      out.write("            overflow-x: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page {\n");
      out.write("            min-height: 100vh;\n");
      out.write("            padding: 40px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .top-nav {\n");
      out.write("            max-width: 1200px;\n");
      out.write("            margin: 0 auto 32px auto;\n");
      out.write("\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .brand {\n");
      out.write("            font-size: 24px;\n");
      out.write("            font-weight: 700;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .brand span {\n");
      out.write("            color: #818cf8;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .back-button {\n");
      out.write("            padding: 11px 18px;\n");
      out.write("            border-radius: 11px;\n");
      out.write("\n");
      out.write("            background:\n");
      out.write("                rgba(255,255,255,0.08);\n");
      out.write("\n");
      out.write("            border:\n");
      out.write("                1px solid rgba(255,255,255,0.10);\n");
      out.write("\n");
      out.write("            color: white;\n");
      out.write("            text-decoration: none;\n");
      out.write("            transition: 0.25s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .back-button:visited {\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .back-button:hover {\n");
      out.write("            background:\n");
      out.write("                rgba(99,102,241,0.18);\n");
      out.write("\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .header {\n");
      out.write("            max-width: 1200px;\n");
      out.write("            margin: 0 auto 30px auto;\n");
      out.write("\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .heading h1 {\n");
      out.write("            font-size: 32px;\n");
      out.write("            margin-bottom: 7px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .heading p {\n");
      out.write("            color: #94a3b8;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .staff-box {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 12px;\n");
      out.write("\n");
      out.write("            padding: 10px 16px;\n");
      out.write("\n");
      out.write("            background:\n");
      out.write("                rgba(255,255,255,0.08);\n");
      out.write("\n");
      out.write("            border:\n");
      out.write("                1px solid rgba(255,255,255,0.10);\n");
      out.write("\n");
      out.write("            border-radius: 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .avatar {\n");
      out.write("            width: 44px;\n");
      out.write("            height: 44px;\n");
      out.write("            border-radius: 50%;\n");
      out.write("\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("\n");
      out.write("            background:\n");
      out.write("                linear-gradient(\n");
      out.write("                    135deg,\n");
      out.write("                    #6366f1,\n");
      out.write("                    #0ea5e9\n");
      out.write("                );\n");
      out.write("\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .staff-small {\n");
      out.write("            color: #94a3b8;\n");
      out.write("            font-size: 12px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .message {\n");
      out.write("            max-width: 1200px;\n");
      out.write("            margin: 0 auto 22px auto;\n");
      out.write("\n");
      out.write("            padding: 14px 18px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("\n");
      out.write("            background:\n");
      out.write("                rgba(99,102,241,0.12);\n");
      out.write("\n");
      out.write("            border:\n");
      out.write("                1px solid rgba(129,140,248,0.18);\n");
      out.write("\n");
      out.write("            color: #c7d2fe;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .summary-grid {\n");
      out.write("            max-width: 1200px;\n");
      out.write("            margin: 0 auto 28px auto;\n");
      out.write("\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(3,1fr);\n");
      out.write("            gap: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .summary-card {\n");
      out.write("            padding: 23px;\n");
      out.write("            border-radius: 18px;\n");
      out.write("\n");
      out.write("            background:\n");
      out.write("                rgba(255,255,255,0.08);\n");
      out.write("\n");
      out.write("            border:\n");
      out.write("                1px solid rgba(255,255,255,0.10);\n");
      out.write("\n");
      out.write("            box-shadow:\n");
      out.write("                0 15px 35px rgba(0,0,0,0.18);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .summary-label {\n");
      out.write("            color: #94a3b8;\n");
      out.write("            font-size: 12px;\n");
      out.write("            margin-bottom: 12px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .summary-value {\n");
      out.write("            font-size: 22px;\n");
      out.write("            font-weight: 700;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .present-status {\n");
      out.write("            display: inline-block;\n");
      out.write("\n");
      out.write("            padding: 7px 13px;\n");
      out.write("            border-radius: 25px;\n");
      out.write("\n");
      out.write("            background:\n");
      out.write("                rgba(34,197,94,0.15);\n");
      out.write("\n");
      out.write("            color: #86efac;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .pending-status {\n");
      out.write("            display: inline-block;\n");
      out.write("\n");
      out.write("            padding: 7px 13px;\n");
      out.write("            border-radius: 25px;\n");
      out.write("\n");
      out.write("            background:\n");
      out.write("                rgba(245,158,11,0.15);\n");
      out.write("\n");
      out.write("            color: #fcd34d;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .main-grid {\n");
      out.write("            max-width: 1200px;\n");
      out.write("            margin: auto;\n");
      out.write("\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: 1fr 1.6fr;\n");
      out.write("            gap: 25px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .panel {\n");
      out.write("            padding: 28px;\n");
      out.write("            border-radius: 20px;\n");
      out.write("\n");
      out.write("            background:\n");
      out.write("                rgba(255,255,255,0.08);\n");
      out.write("\n");
      out.write("            border:\n");
      out.write("                1px solid rgba(255,255,255,0.10);\n");
      out.write("\n");
      out.write("            box-shadow:\n");
      out.write("                0 18px 45px rgba(0,0,0,0.20);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .panel-title {\n");
      out.write("            font-size: 21px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            margin-bottom: 6px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .panel-description {\n");
      out.write("            color: #94a3b8;\n");
      out.write("            font-size: 13px;\n");
      out.write("            margin-bottom: 25px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .attendance-box {\n");
      out.write("            padding: 18px;\n");
      out.write("            margin-bottom: 16px;\n");
      out.write("\n");
      out.write("            border-radius: 14px;\n");
      out.write("\n");
      out.write("            background:\n");
      out.write("                rgba(255,255,255,0.05);\n");
      out.write("\n");
      out.write("            border:\n");
      out.write("                1px solid rgba(255,255,255,0.07);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .box-label {\n");
      out.write("            color: #64748b;\n");
      out.write("            font-size: 12px;\n");
      out.write("            margin-bottom: 8px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .box-value {\n");
      out.write("            font-size: 18px;\n");
      out.write("            font-weight: 600;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .register-button {\n");
      out.write("            width: 100%;\n");
      out.write("            border: none;\n");
      out.write("            padding: 14px;\n");
      out.write("\n");
      out.write("            border-radius: 11px;\n");
      out.write("\n");
      out.write("            background:\n");
      out.write("                linear-gradient(\n");
      out.write("                    135deg,\n");
      out.write("                    #6366f1,\n");
      out.write("                    #4f46e5\n");
      out.write("                );\n");
      out.write("\n");
      out.write("            color: white;\n");
      out.write("            font-size: 15px;\n");
      out.write("            font-weight: 600;\n");
      out.write("\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: 0.25s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .register-button:hover {\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("\n");
      out.write("            box-shadow:\n");
      out.write("                0 12px 30px rgba(79,70,229,0.40);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .register-button:disabled {\n");
      out.write("            opacity: 0.55;\n");
      out.write("            cursor: not-allowed;\n");
      out.write("            transform: none;\n");
      out.write("            box-shadow: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        table {\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        th,\n");
      out.write("        td {\n");
      out.write("            padding: 14px 12px;\n");
      out.write("\n");
      out.write("            border-bottom:\n");
      out.write("                1px solid rgba(255,255,255,0.08);\n");
      out.write("\n");
      out.write("            text-align: left;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        th {\n");
      out.write("            color: #94a3b8;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .history-status {\n");
      out.write("            color: #86efac;\n");
      out.write("            font-weight: 600;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .empty {\n");
      out.write("            color: #64748b;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @media(max-width:900px) {\n");
      out.write("\n");
      out.write("            .summary-grid {\n");
      out.write("                grid-template-columns: 1fr;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .main-grid {\n");
      out.write("                grid-template-columns: 1fr;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @media(max-width:650px) {\n");
      out.write("\n");
      out.write("            .page {\n");
      out.write("                padding: 20px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .top-nav,\n");
      out.write("            .header {\n");
      out.write("                flex-direction: column;\n");
      out.write("                align-items: flex-start;\n");
      out.write("                gap: 18px;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"page\">\n");
      out.write("\n");
      out.write("    <div class=\"top-nav\">\n");
      out.write("\n");
      out.write("        <div class=\"brand\">\n");
      out.write("            Staff<span>Portal</span>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <a href=\"Sdash.jsp\"\n");
      out.write("           class=\"back-button\">\n");
      out.write("            ← Back to Dashboard\n");
      out.write("        </a>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"header\">\n");
      out.write("\n");
      out.write("        <div class=\"heading\">\n");
      out.write("\n");
      out.write("            <h1>\n");
      out.write("                Attendance\n");
      out.write("            </h1>\n");
      out.write("\n");
      out.write("            <p>\n");
      out.write("                Register and review your attendance.\n");
      out.write("            </p>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"staff-box\">\n");
      out.write("\n");
      out.write("            <div class=\"avatar\">\n");
      out.write("                ");
      out.print( Staff_Name.substring(0,1).toUpperCase() );
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div>\n");
      out.write("\n");
      out.write("                <strong>\n");
      out.write("                    ");
      out.print( Staff_Name );
      out.write("\n");
      out.write("                </strong>\n");
      out.write("\n");
      out.write("                <div class=\"staff-small\">\n");
      out.write("                    Staff ID #");
      out.print( Staff_ID );
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
 if (!message.equals("")) { 
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"message\">\n");
      out.write("            ");
      out.print( message );
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"summary-grid\">\n");
      out.write("\n");
      out.write("        <div class=\"summary-card\">\n");
      out.write("\n");
      out.write("            <div class=\"summary-label\">\n");
      out.write("                Today's Date\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"summary-value\">\n");
      out.write("                ");
      out.print( formattedDate );
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"summary-card\">\n");
      out.write("\n");
      out.write("            <div class=\"summary-label\">\n");
      out.write("                Attendance Status\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
 if(alreadyRegistered) { 
      out.write("\n");
      out.write("\n");
      out.write("                <div class=\"present-status\">\n");
      out.write("                    ");
      out.print( todayStatus );
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("\n");
      out.write("                <div class=\"pending-status\">\n");
      out.write("                    Not Registered\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"summary-card\">\n");
      out.write("\n");
      out.write("            <div class=\"summary-label\">\n");
      out.write("                Check-In Time\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"summary-value\">\n");
      out.write("                ");
      out.print( todayCheckIn );
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"main-grid\">\n");
      out.write("\n");
      out.write("        <div class=\"panel\">\n");
      out.write("\n");
      out.write("            <div class=\"panel-title\">\n");
      out.write("                Today's Attendance\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"panel-description\">\n");
      out.write("                Register your attendance for today.\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"attendance-box\">\n");
      out.write("\n");
      out.write("                <div class=\"box-label\">\n");
      out.write("                    Staff\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"box-value\">\n");
      out.write("                    ");
      out.print( Staff_Name );
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"attendance-box\">\n");
      out.write("\n");
      out.write("                <div class=\"box-label\">\n");
      out.write("                    Date\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"box-value\">\n");
      out.write("                    ");
      out.print( formattedDate );
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"attendance-box\">\n");
      out.write("\n");
      out.write("                <div class=\"box-label\">\n");
      out.write("                    Current Status\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"box-value\">\n");
      out.write("                    ");
      out.print( todayStatus );
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <form action=\"attendance.jsp\"\n");
      out.write("                  method=\"post\">\n");
      out.write("\n");
      out.write("                <input\n");
      out.write("                    type=\"hidden\"\n");
      out.write("                    name=\"action\"\n");
      out.write("                    value=\"register\"\n");
      out.write("                >\n");
      out.write("\n");
      out.write("                <button\n");
      out.write("                    type=\"submit\"\n");
      out.write("                    class=\"register-button\"\n");
      out.write("\n");
      out.write("                    ");
 if(alreadyRegistered) { 
      out.write("\n");
      out.write("                        disabled\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                >\n");
      out.write("\n");
      out.write("                    ");
 if(alreadyRegistered) { 
      out.write("\n");
      out.write("\n");
      out.write("                        ✓ Attendance Already Registered\n");
      out.write("\n");
      out.write("                    ");
 } else { 
      out.write("\n");
      out.write("\n");
      out.write("                        ✓ Register Attendance\n");
      out.write("\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                </button>\n");
      out.write("\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"panel\">\n");
      out.write("\n");
      out.write("            <div class=\"panel-title\">\n");
      out.write("                Attendance History\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"panel-description\">\n");
      out.write("                Your recent attendance records.\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <table>\n");
      out.write("\n");
      out.write("                <thead>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <th>Date</th>\n");
      out.write("                        <th>Check In</th>\n");
      out.write("                        <th>Status</th>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                </thead>\n");
      out.write("\n");
      out.write("                <tbody>\n");
      out.write("\n");
      out.write("                ");


                    try {

                        psmt = con.prepareStatement(

                            "SELECT attendance_date, " +
                            "check_in_time, status " +
                            "FROM attendance " +
                            "WHERE staff_id = ? " +
                            "ORDER BY attendance_date DESC"
                        );

                        psmt.setInt(
                            1,
                            Staff_ID
                        );

                        rs =
                            psmt.executeQuery();

                        boolean recordsFound =
                            false;

                        while(rs.next()) {

                            recordsFound =
                                true;

                            Date attendanceDate =
                                rs.getDate("attendance_date");

                            Time attendanceTime =
                                rs.getTime("check_in_time");

                            String attendanceStatus =
                                rs.getString("status");

                            String displayTime =
                                "--";

                            if(attendanceTime != null) {

                                displayTime =
                                    attendanceTime
                                    .toLocalTime()
                                    .format(
                                        DateTimeFormatter.ofPattern(
                                            "hh:mm a"
                                        )
                                    );
                            }

                
      out.write("\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("\n");
      out.write("                        <td>\n");
      out.write("                            ");
      out.print( attendanceDate );
      out.write("\n");
      out.write("                        </td>\n");
      out.write("\n");
      out.write("                        <td>\n");
      out.write("                            ");
      out.print( displayTime );
      out.write("\n");
      out.write("                        </td>\n");
      out.write("\n");
      out.write("                        <td>\n");
      out.write("\n");
      out.write("                            <span class=\"history-status\">\n");
      out.write("                                ");
      out.print( attendanceStatus );
      out.write("\n");
      out.write("                            </span>\n");
      out.write("\n");
      out.write("                        </td>\n");
      out.write("\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                ");


                        }

                        if(!recordsFound) {

                
      out.write("\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("\n");
      out.write("                        <td colspan=\"3\"\n");
      out.write("                            class=\"empty\">\n");
      out.write("\n");
      out.write("                            No attendance records available yet.\n");
      out.write("\n");
      out.write("                        </td>\n");
      out.write("\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                ");


                        }

                    } catch(Exception e) {

                
      out.write("\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("\n");
      out.write("                        <td colspan=\"3\"\n");
      out.write("                            class=\"empty\">\n");
      out.write("\n");
      out.write("                            Unable to load attendance history.\n");
      out.write("\n");
      out.write("                        </td>\n");
      out.write("\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                ");


                    }

                
      out.write("\n");
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("\n");
      out.write("            </table>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
