/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2026-09-27 08:45:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("\n");
      out.write("    <meta name=\"viewport\"\n");
      out.write("          content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("    <title>Staff Login</title>\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            min-height: 100vh;\n");
      out.write("\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("\n");
      out.write("            background:\n");
      out.write("                radial-gradient(\n");
      out.write("                    circle at top left,\n");
      out.write("                    rgba(99, 102, 241, 0.32),\n");
      out.write("                    transparent 35%\n");
      out.write("                ),\n");
      out.write("                radial-gradient(\n");
      out.write("                    circle at bottom right,\n");
      out.write("                    rgba(14, 165, 233, 0.24),\n");
      out.write("                    transparent 35%\n");
      out.write("                ),\n");
      out.write("                linear-gradient(\n");
      out.write("                    135deg,\n");
      out.write("                    #0f172a,\n");
      out.write("                    #111827,\n");
      out.write("                    #1e293b\n");
      out.write("                );\n");
      out.write("\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .message-card {\n");
      out.write("\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 430px;\n");
      out.write("\n");
      out.write("            padding: 42px 36px;\n");
      out.write("\n");
      out.write("            text-align: center;\n");
      out.write("\n");
      out.write("            background:\n");
      out.write("                rgba(255,255,255,0.08);\n");
      out.write("\n");
      out.write("            backdrop-filter: blur(18px);\n");
      out.write("\n");
      out.write("            border:\n");
      out.write("                1px solid rgba(255,255,255,0.12);\n");
      out.write("\n");
      out.write("            border-radius: 22px;\n");
      out.write("\n");
      out.write("            box-shadow:\n");
      out.write("                0 25px 60px rgba(0,0,0,0.35);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error-icon {\n");
      out.write("\n");
      out.write("            width: 72px;\n");
      out.write("            height: 72px;\n");
      out.write("\n");
      out.write("            margin: 0 auto 22px;\n");
      out.write("\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("\n");
      out.write("            border-radius: 50%;\n");
      out.write("\n");
      out.write("            background:\n");
      out.write("                rgba(239,68,68,0.15);\n");
      out.write("\n");
      out.write("            border:\n");
      out.write("                1px solid rgba(239,68,68,0.25);\n");
      out.write("\n");
      out.write("            color: #fca5a5;\n");
      out.write("\n");
      out.write("            font-size: 34px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        h2 {\n");
      out.write("            font-size: 28px;\n");
      out.write("            margin-bottom: 12px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        p {\n");
      out.write("            color: #94a3b8;\n");
      out.write("            line-height: 1.6;\n");
      out.write("            margin-bottom: 26px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .primary-btn,\n");
      out.write("        .secondary-btn {\n");
      out.write("\n");
      out.write("            display: block;\n");
      out.write("\n");
      out.write("            width: 100%;\n");
      out.write("\n");
      out.write("            padding: 14px;\n");
      out.write("\n");
      out.write("            border-radius: 11px;\n");
      out.write("\n");
      out.write("            text-decoration: none;\n");
      out.write("\n");
      out.write("            font-weight: 600;\n");
      out.write("\n");
      out.write("            transition: 0.25s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .primary-btn {\n");
      out.write("\n");
      out.write("            background:\n");
      out.write("                linear-gradient(\n");
      out.write("                    135deg,\n");
      out.write("                    #6366f1,\n");
      out.write("                    #4f46e5\n");
      out.write("                );\n");
      out.write("\n");
      out.write("            color: white;\n");
      out.write("\n");
      out.write("            box-shadow:\n");
      out.write("                0 10px 25px rgba(79,70,229,0.35);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .primary-btn:hover {\n");
      out.write("\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("\n");
      out.write("            box-shadow:\n");
      out.write("                0 15px 35px rgba(79,70,229,0.45);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .secondary-btn {\n");
      out.write("\n");
      out.write("            margin-top: 12px;\n");
      out.write("\n");
      out.write("            background:\n");
      out.write("                rgba(255,255,255,0.06);\n");
      out.write("\n");
      out.write("            color: #e2e8f0;\n");
      out.write("\n");
      out.write("            border:\n");
      out.write("                1px solid rgba(255,255,255,0.10);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .secondary-btn:hover {\n");
      out.write("\n");
      out.write("            background:\n");
      out.write("                rgba(255,255,255,0.10);\n");
      out.write("\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error-details {\n");
      out.write("\n");
      out.write("            margin-top: 15px;\n");
      out.write("\n");
      out.write("            color: #fca5a5;\n");
      out.write("\n");
      out.write("            font-size: 13px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");


    Connection con = null;
    PreparedStatement psmt = null;
    ResultSet rs = null;

    try {

        String umobile = request.getParameter("umobile");

        Class.forName("org.postgresql.Driver");

        con = DriverManager.getConnection(
            "jdbc:postgresql://localhost:5432/demoDB",
            "postgres",
            "0617"
        );

        psmt = con.prepareStatement(
            "SELECT * FROM staff WHERE mob = ?"
        );

        psmt.setString(1, umobile);

        rs = psmt.executeQuery();

        if(rs.next()) {

            session.setAttribute(
                "Staff_ID",
                rs.getInt("id")
            );

            session.setAttribute(
                "Staff_Name",
                rs.getString("name")
            );

            session.setAttribute(
                "Staff_Mobile",
                rs.getString("mob")
            );

            session.setAttribute(
                "Staff_Salary",
                rs.getInt("salary")
            );

            response.sendRedirect("Sdash.jsp");
            return;

        } else {


      out.write("\n");
      out.write("\n");
      out.write("<div class=\"message-card\">\n");
      out.write("\n");
      out.write("    <div class=\"error-icon\">\n");
      out.write("        !\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <h2>\n");
      out.write("        Mobile Number Not Registered\n");
      out.write("    </h2>\n");
      out.write("\n");
      out.write("    <p>\n");
      out.write("        We couldn't find an account associated with this mobile number.\n");
      out.write("        Please check the number and try again, or create a new account.\n");
      out.write("    </p>\n");
      out.write("\n");
      out.write("    <a href=\"Login.html\"\n");
      out.write("       class=\"primary-btn\">\n");
      out.write("        Try Again\n");
      out.write("    </a>\n");
      out.write("\n");
      out.write("    <a href=\"staff.html\"\n");
      out.write("       class=\"secondary-btn\">\n");
      out.write("        Register New Account\n");
      out.write("    </a>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");


        }

    } catch(Exception e) {


      out.write("\n");
      out.write("\n");
      out.write("<div class=\"message-card\">\n");
      out.write("\n");
      out.write("    <div class=\"error-icon\">\n");
      out.write("        !\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <h2>\n");
      out.write("        Something Went Wrong\n");
      out.write("    </h2>\n");
      out.write("\n");
      out.write("    <p>\n");
      out.write("        We were unable to process your login request.\n");
      out.write("    </p>\n");
      out.write("\n");
      out.write("    <div class=\"error-details\">\n");
      out.write("        ");
      out.print( e.getMessage() );
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <br>\n");
      out.write("\n");
      out.write("    <a href=\"Login.html\"\n");
      out.write("       class=\"primary-btn\">\n");
      out.write("        Return to Login\n");
      out.write("    </a>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");


    }


      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
